variable "tooling_target_group_arn" {}
variable "wordpress_target_group_arn" {}
variable "nginx_target_group_arn" {}
variable "ami" {}
variable "region" {}
variable "instance_type" {}
variable "external_lb_security_group_id" {}
variable "internal_lb_security_group_id" {}
variable "bastion_security_group_id" {}
variable "nginx_security_group_id" {}
variable "webservers_security_group_id" {}
variable "public_subnet1_id" {}
variable "public_subnet2_id" {}
variable "private_subnet1_id" {}
variable "private_subnet2_id" {}
variable "tags" {}
variable "name" {}
variable "vpc_id" {}
variable "iam_instance_profile" {}
variable "availability_zone" {}
variable "internal_lb_dns_name" {}